version: '3.5'

services:
  ttrss:
    image: linuxserver/tt-rss:latest
    container_name: ttrss
    external_links:
      - postgres
    networks:
      - web
      - postgres_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - POSTGRES_DB=ttrss
    volumes:
      - ${PERSISTENT_DIR}/config:/config
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.backend=ttrss"
      - "traefik.frontend.rule=Host:rss.${DOMAIN_BASE}"
      - "traefik.frontend.auth.forward.address=https://login.${DOMAIN_BASE}/api/verify?rd=https://login.${DOMAIN_BASE}/%23/"
      - "traefik.frontend.headers.customRequestHeaders=X-ORIGINAL-URL:https://rss.${DOMAIN_BASE}"
      - "traefik.frontend.auth.forward.tls.insecureSkipVerify=true"
      - "traefik.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

networks:
  web:
    external: true
  postgres_network:
    external: true

# vim: tabstop=2 shiftwidth=2 expandtab
